services:

  postgres:
    container_name: nosql_postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=nosql_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5490:5432"
    volumes:
      - nosqldb:/var/lib/postgresql/data

volumes:
  nosqldb: