services:

  postgres:
    container_name: redis-psql
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=redisdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5487:5432"
    volumes:
      - redis:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  redis: